baseurl: "https://scalalang2.github.io/"
languageCode: "ko-kr"
title: "scalalang2"
theme: "hugo-tania"

params:
  socialOptions:
    github: https://github.com/scalalang2
    email: cailhuiris@gmail.com

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true